version: '3'
services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    expose:
      - "9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dev-es-data-test-01:/usr/share/elasticsearch/data

  fastapi:
    container_name: fastapi
    build:
      args:
        appuser: ${APP_IO_USER}
      context: fastapi-solution
      target: dev
    depends_on:
      - es01
    volumes:
      - ./fastapi-solution/src:/app
    env_file: .env.dev
    expose:
      - "8080"

  redis:
    image: redis
    command: redis-server
    container_name: redis
    hostname: redis
    expose:
      - "6379"

  tests:
    build:
      context: tests
    container_name: tests
    volumes:
      - ./tests/functional:/functional
    env_file: .env.dev
    entrypoint: >
      /bin/bash -c "pytest /functional"    

volumes:
  dev-es-data-test-01: